### ISSUE TITLE
lint-and-install complains when using --helm-lint-extra-args

### ISSUE THREAD

**Issue by ctron** [helm/chart-testing#629] opened 2024-02-14 13:09 UTC
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: not relevant

**What happened**:

`ct lint-and-install --help` shows an argument named `--helm-lint-extra-args`:

```
      --helm-lint-extra-args string          Additional arguments for Helm lint subcommand. Must be passed as a single quoted string
                                             (e.g. '--quiet')
```

Making use of that argument make the application fail:

```
Run ct lint-and-install --helm-lint-extra-args "--values values-minikube.yaml --set-string appDomain=$APP_DOMAIN" --namespace $NAMESPACE --charts deploy/k8s/charts/trustification --target-branch main
Error: unknown flag: --helm-lint-extra-args
unknown flag: --helm-lint-extra-args
Error: Process completed with exit code 1.
```

**What you expected to happen**:

I would expect that all arguments listed by `--help` do work.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else we need to know**:

No.

**Comment by cpanato** [comment] 2024-02-14 13:30
thanks for the issue, one quick question, what is the version of the ct that you are using?

**Comment by ctron** [comment] 2024-02-14 13:39
```
Version:         v3.10.1
Git commit:      c35d32b568ba7901e00d3386a231ae2b6e1c2efc
Date:            2023-11-03T12:16:46Z
License:         Apache 2.0
```

**Comment by cpanato** [comment] 2024-02-14 13:52
@ctron thanks
ok, i will take a look

but `--helm-lint-extra-args ` is to set lint extra args and in your example, you are setting helm options for helm options, you should use `helm-extra-set-args` and/or `helm-extra-args`

**Comment by cpanato** [comment] 2024-02-14 14:06
testing

```
$ ct version
Version:         3.10.1
Git commit:      c35d32b568ba7901e00d3386a231ae2b6e1c2efc
Date:            2023-11-02
License:         Apache 2.0
```

ct lint only 
```
$ ct lint --helm-lint-extra-args "--set-string appDomain=tests" --charts test_charts/mutating-deployment-selector/ --target-branch main --validate-maintainers=false
Linting charts...
Version increment checking disabled.

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 nginx => (version: "0.1.0", path: "test_charts/mutating-deployment-selector/")
------------------------------------------------------------------------------------------------------------------------

Linting chart "nginx => (version: \"0.1.0\", path: \"test_charts/mutating-deployment-selector/\")"
Validating /Users/cpanato/code/src/github.com/helm/chart-testing/pkg/chart/test_charts/mutating-deployment-selector/Chart.yaml...
Validation success! 👍
==> Linting test_charts/mutating-deployment-selector/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

------------------------------------------------------------------------------------------------------------------------
 ✔︎ nginx => (version: "0.1.0", path: "test_charts/mutating-deployment-selector/")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

lint-and-install
```
$ ct lint-and-install --helm-lint-extra-args "--set-string appDomain=tests" --namespace default --charts test_charts/mutating-deployment-selector/ --target-branch main --validate-maintainers=false
Linting and installing charts...
Version increment checking disabled.

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 nginx => (version: "0.1.0", path: "test_charts/mutating-deployment-selector/")
------------------------------------------------------------------------------------------------------------------------

Linting chart "nginx => (version: \"0.1.0\", path: \"test_charts/mutating-deployment-selector/\")"
Validating /Users/cpanato/code/src/github.com/helm/chart-testing/pkg/chart/test_charts/mutating-deployment-selector/Chart.yaml...
Validation success! 👍
==> Linting test_charts/mutating-deployment-selector/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
Installing chart "nginx => (version: \"0.1.0\", path: \"test_charts/mutating-deployment-selector/\")"...
NAME: mutating-deployment-selector-oct5grhyxt
LAST DEPLOYED: Wed Feb 14 15:04:56 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
deployment "mutating-deployment-selector-oct5grhyxt-nginx" successfully rolled out
NAME: mutating-deployment-selector-oct5grhyxt
LAST DEPLOYED: Wed Feb 14 15:04:56 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE:     mutating-deployment-selector-oct5grhyxt-nginx-test-connection
Last Started:   Wed Feb 14 15:05:02 2024
Last Completed: Wed Feb 14 15:05:07 2024
Phase:          Succeeded
....
```


i was not able to reproduce the issue, maybe if this repo that you are trying is public then i can check that as well

**Comment by ctron** [comment] 2024-02-14 15:07
The repo is public, not sure if it's easy to reproduce though: https://github.com/trustification/trustification/pull/1089 … let met do some checks.

**Comment by ctron** [comment] 2024-02-14 15:09
Hm ok … the chart-testing action seems to pull in a different version. Close, but different:

```
Version:	 v3.10.0
Git commit:	 0cb17e5aa89e2d6cf49cb4e7f09b602af58adfbb
Date:		 2023-10-31T14:27:21Z
License:	 Apache 2.0
```

**Comment by ctron** [comment] 2024-02-14 15:11
Sorry for the noise, that's most likely it. As it's listed as a change for 3.10.1: https://github.com/helm/chart-testing/pull/605

**Comment by cpanato** [comment] 2024-02-14 15:19
not a problem, will close this

**Closed by cpanato** 2024-02-14 15:19 UTC
Labels: bug
