### ISSUE TITLE
BUG REPORT: Invalid Semantic Version | Helm V2 

### ISSUE THREAD

**Issue by MateusAmin** [helm/chart-testing#213] opened 2020-03-12 17:14 UTC
I get a invalid semantic version error on the latest helm v2 and ct 3 beta 2 release. Happens after helm version --short is called.

helm version --short
Client: v2.16.3+g1ee0254
Server: v2.16.3+g1ee0254

I suppose it does not like +g1ee0254.

**Comment by jgleonard** [comment] 2020-03-12 17:23
Came to report the same issue on Helm3, however it only seems broken when I run via CI.  Locally I cannot reproduce.

ct version 3.0.0 beta 2

```
# helm version --short
v3.0.2+g19e47ee
```

**Comment by unguiculus** [comment] 2020-03-21 14:12
What exactly are you trying to do? How is this related to chart-testing?

**Comment by jgleonard** [comment] 2020-03-23 15:50
@unguiculus for me, I was doing a ct lint and on the helm version detection, it crapped out.

`$ ct lint $ARGS --chart-dirs . --validate-maintainers=false
 Linting charts...
 ------------------------------------------------------------------------------------------------------------------------
  Configuration
 ------------------------------------------------------------------------------------------------------------------------
 Remote: origin
 TargetBranch: master
 BuildId: 
 LintConf: lintconf.yaml
 ChartYamlSchema: chart_schema.yaml
 ValidateMaintainers: false
 ValidateChartSchema: true
 ValidateYaml: true
 CheckVersionIncrement: true
 ProcessAllCharts: false
 Charts: []
 ChartRepos: []
 ChartDirs: [.]
 ExcludedCharts: []
 HelmExtraArgs: 
 HelmRepoExtraArgs: []
 Debug: true
 Upgrade: false
 SkipMissingValues: false
 Namespace: 
 ReleaseLabel: 
 ------------------------------------------------------------------------------------------------------------------------
 >>> helm version --short
 Error: Invalid Semantic Version
 Usage:
   ct lint [flags]
 Flags:
       --all                            Process all charts except those explicitly excluded.
                                        Disables changed charts detection and version increment checking
       --chart-dirs strings             Directories containing Helm charts. May be specified multiple times
                                        or separate values with commas (default [charts])
       --chart-repos strings            Additional chart repositories for dependency resolutions.
                                        Repositories should be formatted as 'name=url' (ex: local=http://127.0.0.1:8879/charts).
                                        May be specified multiple times or separate values with commas
       --chart-yaml-schema string       The schema for chart.yml validation. If not specified, 'chart_schema.yaml'
                                        is searched in the current directory, '$HOME/.ct', and '/etc/ct', in
                                        that order.
       --charts strings                 Specific charts to test. Disables changed charts detection and
                                        version increment checking. May be specified multiple times
                                        or separate values with commas
       --check-version-increment        Activates a check for chart version increments (default: true) (default true)
       --config string                  Config file
       --debug                          Print CLI calls of external tools to stdout (Note: depending on helm-extra-args
                                        passed, this may reveal sensitive data)
       --excluded-charts strings        Charts that should be skipped. May be specified multiple times
                                        or separate values with commas
       --helm-repo-extra-args strings   Additional arguments for the 'helm repo add' command to be
                                        specified on a per-repo basis with an equals sign as delimiter
                                        (e.g. 'myrepo=--username test --password secret'). May be specified
                                        multiple times or separate values with commas
   -h, --help                           help for lint
       --lint-conf string               The config file for YAML linting. If not specified, 'lintconf.yaml'
                                        is searched in the current directory, '$HOME/.ct', and '/etc/ct', in
                                        that order
       --remote string                  The name of the Git remote used to identify changed charts (default "origin")
       --target-branch string           The name of the target branch used to identify changed charts (default "master")
       --validate-chart-schema          Enable schema validation of 'Chart.yaml' using Yamale (default: true) (default true)
       --validate-maintainers           Enable validation of maintainer account names in chart.yml (default: true).
                                        Works for GitHub, GitLab, and Bitbucket (default true)
       --validate-yaml                  Enable linting of 'Chart.yaml' and values files (default: true) (default true)
 Invalid Semantic Version
 ERROR: Job failed: command terminated with exit code 1`

**Comment by unguiculus** [comment] 2020-03-23 19:33
I debugged this. The problem is probably that your kube-context points to a config file that does not exist. I filed an issue with Helm: https://github.com/helm/helm/issues/7796

**Comment by jgleonard** [comment] 2020-03-24 15:04
@unguiculus Ohhh great catch.  Completely explains it.   Thanks.

**Comment by unguiculus** [comment] 2020-03-28 08:20
Closing this since it is an issue with Helm itself.

**Closed by unguiculus** 2020-03-28 08:20 UTC

**Comment by jenting** [comment] 2020-12-31 01:55
Is there any way we could workaround this issue?
