### ISSUE TITLE
ct install fails with helm v 3.0.0

### ISSUE THREAD

**Issue by Vikash082** [helm/chart-testing#188] opened 2019-11-20 08:44 UTC
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Yes

**Version of Helm and Kubernetes**:
```
helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-docker-1", GitCommit:"8249259df545d6e853b7de9d050a34ec24e8b2f5", GitTreeState:"clean", BuildDate:"2019-02-05T21:33:23Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
Executed these steps:

1. Installed latest helm from the release binary
2. Installed latest ct using release binary
3. git clone https://github.com/helm/charts.git
4. cd charts
5. ct install  --chart-dirs incubator  --all

Step 5 resulted in this error:
```
Installing charts...
Version increment checking disabled.
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: origin
TargetBranch: master
BuildId:
LintConf: /root/.ct/lintconf.yaml
ChartYamlSchema: /root/.ct/chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: false
ValidateYaml: false
CheckVersionIncrement: false
ProcessAllCharts: true
Charts: []
ChartRepos: []
ChartDirs: [incubator]
ExcludedCharts: []
HelmExtraArgs:
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace:
ReleaseLabel: app.kubernetes.io/instance
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 artifactory => (version: "5.2.1", path: "incubator/artifactory")
 aws-alb-ingress-controller => (version: "0.1.11", path: "incubator/aws-alb-ingress-controller")
 azuremonitor-containers => (version: "2.4.0", path: "incubator/azuremonitor-containers")
 burrow => (version: "0.3.3", path: "incubator/burrow")
 buzzfeed-sso => (version: "0.1.1", path: "incubator/buzzfeed-sso")
 cassandra => (version: "0.13.3", path: "incubator/cassandra")
 cassandra-operator => (version: "0.3.2", path: "incubator/cassandra-operator")
 cassandra-reaper => (version: "0.2.1", path: "incubator/cassandra-reaper")
 chartmuseum => (version: "1.1.1", path: "incubator/chartmuseum")
 check-mk => (version: "0.2.1", path: "incubator/check-mk")
 common => (version: "0.0.5", path: "incubator/common")
 couchdb => (version: "1.3.1", path: "incubator/couchdb")
 distribution => (version: "0.3.1", path: "incubator/distribution")
 drone => (version: "1.1.1", path: "incubator/drone")
 druid => (version: "0.1.1", path: "incubator/druid")
 elastic-stack => (version: "0.11.1", path: "incubator/elastic-stack")
 elasticsearch => (version: "1.10.2", path: "incubator/elasticsearch")
 elasticsearch-curator => (version: "0.4.3", path: "incubator/elasticsearch-curator")
 etcd => (version: "0.7.3", path: "incubator/etcd")
 fluentd => (version: "0.2.1", path: "incubator/fluentd")
 fluentd-cloudwatch => (version: "0.11.1", path: "incubator/fluentd-cloudwatch")
 fluentd-elasticsearch => (version: "2.0.7", path: "incubator/fluentd-elasticsearch")
 gogs => (version: "0.7.11", path: "incubator/gogs")
 goldfish => (version: "0.2.7", path: "incubator/goldfish")
 haproxy-ingress => (version: "0.0.20", path: "incubator/haproxy-ingress")
 honeydipper => (version: "0.1.3", path: "incubator/honeydipper")
 hoverfly => (version: "0.1.1", path: "incubator/hoverfly")
 istio => (version: "0.2.13-chart4", path: "incubator/istio")
 jaeger => (version: "0.13.3", path: "incubator/jaeger")
 jenkins-operator => (version: "0.3.0", path: "incubator/jenkins-operator")
 kafka => (version: "0.20.3", path: "incubator/kafka")
 keycloak => (version: "0.6.0", path: "incubator/keycloak")
 keycloak-proxy => (version: "0.0.1", path: "incubator/keycloak-proxy")
 kube-downscaler => (version: "0.3.0", path: "incubator/kube-downscaler")
 kube-janitor => (version: "0.1.0", path: "incubator/kube-janitor")
 kube-registry-proxy => (version: "0.3.1", path: "incubator/kube-registry-proxy")
 kubeless => (version: "2.1.0", path: "incubator/kubeless")
 kubernetes-vault => (version: "0.2.1", path: "incubator/kubernetes-vault")
 kubewatch => (version: "0.2.3", path: "incubator/kubewatch")
 logstash => (version: "0.9.6", path: "incubator/logstash")
 mysqlha => (version: "1.0.0", path: "incubator/mysqlha")
 oauth-proxy => (version: "0.1.8", path: "incubator/oauth-proxy")
 orientdb => (version: "0.1.2", path: "incubator/orientdb")
 patroni => (version: "0.15.0", path: "incubator/patroni")
 puppet-forge => (version: "0.1.8", path: "incubator/puppet-forge")
 raw => (version: "0.2.3", path: "incubator/raw")
 redis-cache => (version: "0.5.0", path: "incubator/redis-cache")
 riemann => (version: "0.1.2", path: "incubator/riemann")
 rundeck => (version: "0.1.2", path: "incubator/rundeck")
 schema-registry => (version: "1.1.7", path: "incubator/schema-registry")
 sentry-kubernetes => (version: "0.2.2", path: "incubator/sentry-kubernetes")
 solr => (version: "1.3.1", path: "incubator/solr")
 sparkoperator => (version: "0.4.7", path: "incubator/sparkoperator")
 spring-cloud-data-flow => (version: "0.2.7", path: "incubator/spring-cloud-data-flow")
 tensorflow-inception => (version: "0.4.1", path: "incubator/tensorflow-inception")
 vault => (version: "0.23.2", path: "incubator/vault")
 vaultingkube => (version: "0.1.2", path: "incubator/vaultingkube")
 webpagetest-agent => (version: "0.2.0", path: "incubator/webpagetest-agent")
 webpagetest-server => (version: "0.2.1", path: "incubator/webpagetest-server")
 xray => (version: "0.3.2", path: "incubator/xray")
 zookeeper => (version: "2.1.1", path: "incubator/zookeeper")
------------------------------------------------------------------------------------------------------------------------

Error: unknown flag: --client-only
Error installing charts: Error initializing Helm: Error waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
```
**What you expected to happen**:

Intention was to test and install all the charts on my local kubernetes cluster.

**How to reproduce it** (as minimally and precisely as possible):
Steps 1 to 5 will reproduce this.

**Comment by scottrigby** [comment] 2019-12-17 18:27
Can you please test with the [v3.0.0-beta.1](https://github.com/helm/chart-testing/releases/tag/v3.0.0-beta.1) release?

**Comment by rgreinho** [comment] 2020-01-28 19:39
I get the same error message using `quay.io/helmpack/chart-testing:v3.0.0-beta.1` in github actions.

```
2020-01-28T19:07:22.2673506Z ##[group]Run helm/chart-testing-action@v1.0.0-alpha.3
2020-01-28T19:07:22.2673644Z with:
2020-01-28T19:07:22.2673752Z   image: quay.io/helmpack/chart-testing:v3.0.0-beta.1
2020-01-28T19:07:22.2673848Z   command: lint
2020-01-28T19:07:22.2673950Z ##[endgroup]
2020-01-28T19:07:23.1964341Z Unable to find image 'quay.io/helmpack/chart-testing:v3.0.0-beta.1' locally
2020-01-28T19:07:23.1964487Z Running ct container...
2020-01-28T19:07:23.2538654Z v3.0.0-beta.1: Pulling from helmpack/chart-testing
2020-01-28T19:07:23.2555143Z 89d9c30c1d48: Already exists
2020-01-28T19:07:23.2598576Z 9c63575de9ce: Pulling fs layer
2020-01-28T19:07:23.2601061Z 5fb25cb35289: Pulling fs layer
2020-01-28T19:07:23.2603059Z e3c955847c0d: Pulling fs layer
2020-01-28T19:07:23.2605050Z 6b1f051877f9: Pulling fs layer
2020-01-28T19:07:23.2606820Z 71ecd1f42ddf: Pulling fs layer
2020-01-28T19:07:23.2608714Z da76d5035805: Pulling fs layer
2020-01-28T19:07:23.2610555Z dc347a6e778c: Pulling fs layer
2020-01-28T19:07:23.2612839Z 9584376fbeab: Pulling fs layer
2020-01-28T19:07:23.2613130Z 71ecd1f42ddf: Waiting
2020-01-28T19:07:23.2613629Z da76d5035805: Waiting
2020-01-28T19:07:23.2613889Z dc347a6e778c: Waiting
2020-01-28T19:07:23.2613974Z 9584376fbeab: Waiting
2020-01-28T19:07:23.2614151Z 6b1f051877f9: Waiting
2020-01-28T19:07:23.5693588Z 5fb25cb35289: Download complete
2020-01-28T19:07:23.7067607Z e3c955847c0d: Verifying Checksum
2020-01-28T19:07:23.7067942Z e3c955847c0d: Download complete
2020-01-28T19:07:24.3947617Z 9c63575de9ce: Verifying Checksum
2020-01-28T19:07:24.3947977Z 9c63575de9ce: Download complete
2020-01-28T19:07:24.5185446Z 6b1f051877f9: Verifying Checksum
2020-01-28T19:07:24.5185734Z 6b1f051877f9: Download complete
2020-01-28T19:07:24.5899605Z 71ecd1f42ddf: Verifying Checksum
2020-01-28T19:07:24.5925431Z 71ecd1f42ddf: Download complete
2020-01-28T19:07:24.6102121Z da76d5035805: Verifying Checksum
2020-01-28T19:07:24.7393829Z da76d5035805: Download complete
2020-01-28T19:07:24.7394254Z dc347a6e778c: Verifying Checksum
2020-01-28T19:07:24.7394491Z dc347a6e778c: Download complete
2020-01-28T19:07:25.6478263Z 9c63575de9ce: Pull complete
2020-01-28T19:07:25.6764342Z 9584376fbeab: Verifying Checksum
2020-01-28T19:07:25.6764481Z 9584376fbeab: Download complete
2020-01-28T19:07:25.7094608Z 5fb25cb35289: Pull complete
2020-01-28T19:07:25.7546649Z e3c955847c0d: Pull complete
2020-01-28T19:07:26.1406309Z 6b1f051877f9: Pull complete
2020-01-28T19:07:26.4411795Z 71ecd1f42ddf: Pull complete
2020-01-28T19:07:26.4813211Z da76d5035805: Pull complete
2020-01-28T19:07:26.5130775Z dc347a6e778c: Pull complete
2020-01-28T19:07:26.6456515Z 9584376fbeab: Pull complete
2020-01-28T19:07:26.6486927Z Digest: sha256:1c0297bc5d40fa4631a8c715b90312466bb9ca1479521230166d4bbda8c352c1
2020-01-28T19:07:26.6508361Z Status: Downloaded newer image for quay.io/helmpack/chart-testing:v3.0.0-beta.1
2020-01-28T19:07:29.6462406Z f925ea4150e02520fe2c79161d531016c32a128eb9c67c11afbb4acc645eaa1a
2020-01-28T19:07:29.8355286Z 
2020-01-28T19:07:30.1321981Z Error: unknown flag: --client-only
2020-01-28T19:07:30.1502742Z Removing ct container...
2020-01-28T19:07:30.2851513Z Done!
2020-01-28T19:07:30.2932533Z ##[error]Node run failed with exit code 1
2020-01-28T19:07:30.2975547Z Cleaning up orphan processes
```

**Comment by unguiculus** [comment] 2020-01-31 19:46
The flag `--client-only` is not available in Helm 3 anymore and chart-testing no longer uses it. It seems you're still using it in your scripts.

**Comment by rgreinho** [comment] 2020-01-31 19:56
I don't think I am.

Here is my action:
```
- name: Run chart-testing (install)
   uses: helm/chart-testing-action@v1.0.0-alpha.3
    with:
      image: quay.io/helmpack/chart-testing:v3.0.0-beta.1
      command: install
```

**Comment by estahn** [comment] 2020-02-26 02:22
@unguiculus https://github.com/helm/chart-testing-action/blob/master/ct.sh#L147

**Comment by unguiculus** [comment] 2020-02-26 09:02
OK, I see. The problem is not with chart-testing per se, but with the GitHub action. the action does not support Helm 3 yet.

**Comment by unguiculus** [comment] 2020-02-26 09:03
Accidentally hit the close button, but I do think we can close this issue here.

**Comment by estahn** [comment] 2020-02-26 09:30
@unguiculus I think that makes sense. 👍

**Closed** 2020-02-26 09:47 UTC

**Comment by HexF** [comment] 2020-03-27 04:36
FYI - I did some hacky patching to get Helm 3 support - https://github.com/HexF/chart-testing-action

**Comment by scottrigby** [comment] 2020-07-25 21:55
For anyone looking at this older issue: the action supports Helm 3 as of [helm/chart-testing-action@v1.0.0-rc.1](https://github.com/helm/chart-testing-action/releases/tag/v1.0.0-rc.1).
