### ISSUE TITLE
ct install error while uninstalling with --helm-extra-args

### ISSUE THREAD

**Issue by jubeergon** [helm/chart-testing#322] opened 2021-02-12 13:59 UTC
**Version of Helm and Kubernetes**:
helm version: v3.4.0
kubectl version: v1.20.2
ct version:  helm/chart-testing-action@v2.0.1

**What happened**:
When using ct install with --helm-extra-args --set the uninstall of the helm chart gives an error. 
```
helm uninstall helm-chart --namespace default --set key=value
Error: Error installing charts: Error processing charts
Error: unknown flag: --set
Error deleting Helm release: Error waiting for process: exit status 1
```

**What you expected to happen**:
The expectation was that the helm chart could be uninstalled correctly. 

**How to reproduce it** (as minimally and precisely as possible):
Use ```ct install``` with an ```--helm-extra-args``` that is not available in the ```helm uninstall``` command but can be used in ```helm install```.  

**Anything else we need to know**:
I guess the issue is because the same variable is used in the following code snippets:

Uninstall: 
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L81

Install/Upgrade: 
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L58
https://github.com/helm/chart-testing/blob/e84e88cf8bd04ac91000fd675d4cfc2ddf69ba96/pkg/tool/helm.go#L67

**Comment by smlx** [comment] 2021-02-14 16:40
I believe this is a duplicate of #171

**Comment by alespour** [comment] 2021-12-07 10:50
Or duplicate of #212

**Closed** 2022-03-23 09:24 UTC
