### ISSUE TITLE
unknown flag when chart uninstalled

### ISSUE THREAD

**Issue by vmanyushin** [helm/chart-testing#212] opened 2020-03-12 11:36 UTC
BUG REPORT

ct version 3.0.0-beta2

**What happened**:
```
ct lint-and-install --chart-dirs $(pwd) --validate-maintainers=false --helm-extra-args="--values redis/ci/vault-values.yaml" --charts redis  --debug

...
Deleting release 'redis-5xuikf4s43'...
>>> helm uninstall redis-5xuikf4s43 --namespace redis-5xuikf4s43 --values redis/ci/vault-values.yaml
Error: unknown flag: --values
Error deleting Helm release: Error waiting for process: exit status 1
Deleting namespace 'redis-5xuikf4s43'...
>>> kubectl delete namespace redis-5xuikf4s43 --timeout 180s
namespace "redis-5xuikf4s43" deleted
>>> kubectl get namespace redis-5xuikf4s43
Namespace 'redis-5xuikf4s43' terminated.
Error: Error linting and installing charts: Error processing charts
```

i think extra args must not be present in uninstall part.

**Comment by unguiculus** [comment] 2020-03-21 14:19
This is because you pass that in as `--helm-axtra-args`. Values files for testing chart must be in the `ci` folder within the chart's directory. Extra args are not meant to be used to pass in values files. This flag was originally added so one could pass in TLS args with Helm 2.

**Comment by rawkode** [comment] 2020-07-08 14:33
@unguiculus That's unfortunate, as we're hitting this problem too. We need to be able to use `--set`, which fails during uninstall, to pass through a secret that is required for one of the charts to pass successfully.

**Comment by itewk** [comment] 2020-11-20 13:22
related but not exactly the same...https://github.com/helm/chart-testing/issues/301

**Comment by ahmetkaftan** [comment] 2020-12-13 15:40
I've also hit the same issue when I used `--set` flag in `extraArgs` 
```
Deleting release 'mychart-5uade0o099'...
>>> helm uninstall mychart-5uade0o099 --namespace mychart-5uade0o099  --set kafka.replicas=1 --set cassandra.jvm.maxHeapSize=1G --set cassandra.jvm.newHeapSize=200M --timeout 10m
Error: unknown flag: --set
```

**Comment by smlx** [comment] 2020-12-14 05:32
I think this is a duplicate of #171

**Closed** 2022-03-23 09:24 UTC
